"""Add Cliente_Usuario_ID

Revision ID: 0cde9858a5f6
Revises: 0bfc31b64ede
Create Date: 2025-11-05 09:58:40.948259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cde9858a5f6'
down_revision: Union[str, Sequence[str], None] = '0bfc31b64ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('contador_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'contadores', ['contador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'contador_id')
    # ### end Alembic commands ###
