"""CNPJ e Tel voltando ser string

Revision ID: 1563c74d0ccc
Revises: a9c1feed9799
Create Date: 2025-11-13 10:38:00.910893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1563c74d0ccc'
down_revision: Union[str, Sequence[str], None] = 'a9c1feed9799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'cnpj',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=14),
               nullable=True)
    op.alter_column('clientes', 'telefone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=11),
               existing_nullable=True)
    op.drop_constraint(op.f('clientes_cnpj_key'), 'clientes', type_='unique')
    op.drop_constraint(op.f('clientes_telefone_key'), 'clientes', type_='unique')
    op.create_index(op.f('ix_clientes_cnpj'), 'clientes', ['cnpj'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_cnpj'), table_name='clientes')
    op.create_unique_constraint(op.f('clientes_telefone_key'), 'clientes', ['telefone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('clientes_cnpj_key'), 'clientes', ['cnpj'], postgresql_nulls_not_distinct=False)
    op.alter_column('clientes', 'telefone',
               existing_type=sa.String(length=11),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('clientes', 'cnpj',
               existing_type=sa.String(length=14),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
