"""CNPJ/TEL virando string

Revision ID: e30e4f44f47a
Revises: ffacaabf10ec
Create Date: 2025-11-13 09:15:11.930031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30e4f44f47a'
down_revision: Union[str, Sequence[str], None] = 'ffacaabf10ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE clientes ALTER COLUMN cnpj TYPE INTEGER USING cnpj::integer;")
    op.execute("ALTER TABLE clientes ALTER COLUMN telefone TYPE INTEGER USING telefone::integer;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE clientes ALTER COLUMN telefone TYPE INTEGER USING telefone::integer;")
    op.execute("ALTER TABLE clientes ALTER COLUMN cnpj TYPE INTEGER USING cnpj::integer;")
    # ### end Alembic commands ###
