"""Colocar nullable em machine_id

Revision ID: fba54d056fe2
Revises: 5585bf3d02d1
Create Date: 2025-11-13 11:00:17.209767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba54d056fe2'
down_revision: Union[str, Sequence[str], None] = '5585bf3d02d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contadores', 'machine_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contadores', 'machine_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
