"""Add Telefone Column

Revision ID: ffacaabf10ec
Revises: 2f4befac0ab2
Create Date: 2025-11-11 17:03:43.562683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffacaabf10ec'
down_revision: Union[str, Sequence[str], None] = '2f4befac0ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('telefone', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'clientes', ['telefone'])
    op.alter_column('contadores', 'machine_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contadores', 'machine_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_column('clientes', 'telefone')
    # ### end Alembic commands ###
